import Home from './Home/HomePage'
import CartPage from './CartPage'
import Login from './Login'
import Payment from './PaymentPage/Payment'
import Register from './Register'
import ProductsPage from './Products/ProductsPage'
import EachProduct from './ProductDetail/EachProductPage'
import NotFoundPage from './NotFoundPage'
import Orders from './Orders'
export { Orders, Home, CartPage, Login, ProductsPage, EachProduct, Register, Payment, NotFoundPage }